version: '2'
services:
  
#Piwik
  piwik-db:
    image: mariadb
    volumes:
    - './data/piwik/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: $PIWIK_MYSQL_ROOT_PASSWORD

  piwik:
    image: piwik
    links:
     - piwik-db
    volumes:
     - './data/piwik/config:/var/www/html/config'
     - './ssmtp.conf:/etc/ssmtp/ssmtp.conf'
     - './revaliases:/etc/ssmtp/revaliases'

  piwik-cron:
    image: piwik
    links:
     - piwik-db
    volumes_from:
     - piwik
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'

  serve-piwik:
    image: nginx
    volumes:
    - './conf/nginx/nginx-piwik.conf:/etc/nginx/nginx.conf:ro'
    ports:
    - '8081:8081'
    links:
    - piwik
    volumes_from:
    - piwik:ro

#Wordpress
  wordpress-db:
    image: mariadb
    volumes:
    - './data/wordpress/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: $WORDPRESS_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: $WORDPRESS_MYSQL_USER
      MYSQL_PASSWORD: $WORDPRESS_MYSQL_PASSWORD

  wordpress:
    image: ellakcy/wordpressswithplugins
    volumes:
      - './data/wordpress/www:/var/www/html'
    ports:
      - '8080:80'
    links:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:/var/run/mysqld/mysqld.sock
      WORDPRESS_DB_USER: $WORDPRESS_MYSQL_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_MYSQL_PASSWORD
      WORDPRESS_ADMIN_USERNAME: $WORDPRESS_ADMIN_USER
      WORDPRESS_ADMIN_PASSWORD: $WORDPRESS_ADMIN_PASSWORD
      WORDPRESS_URL: $WORDPRESS_URL
      WORDPRESS_VERSION: 4.6.1
