version: '2'
services:
  wordpress-db:
    image: mariadb
    volumes:
    - './data/wordpress/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: $WORDPRESS_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: wordpress
      MYSQL_USER: $WORDPRESS_MYSQL_USER
      MYSQL_PASSWORD: $WORDPRESS_MYSQL_PASSWORD
  wordpress:
    image: wordpress:fpm
    volumes:
    - './data/wordpress/www:/var/www/html'
    links:
    - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:/var/run/mysqld/mysqld.sock
      WORDPRESS_DB_USER: $WORDPRESS_MYSQL_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_MYSQL_PASSWORD
  nginx:
    image: nginx
    volumes:
    - './nginx.conf:/etc/nginx/nginx.conf:ro'
    ports:
    - '8080:80'
    links:
    - wordpress
    volumes_from:
    - wordpress
